import os


LANGUAGE = os.getenv("MACSS_MEDICAL_IE_LANGUAGE", "de")
NER_MODEL_PATH = os.getenv("MACSS_MEDICAL_IE_NER_MODEL_PATH", None)
RE_MODEL_PATH = os.getenv("MACSS_MEDICAL_IE_RE_MODEL_PATH", None)
NEGATION_TRIGGER_PATH = os.getenv("MACSS_MEDICAL_IE_NEGATION_TRIGGER_PATH", None)
DISAMBIGUATOR_PATH = os.getenv("MACSS_MEDICAL_IE_DISAMBIGUATOR_PATH", None)

UMLS_SOLR_HOST = os.getenv("MACSS_MEDICAL_IE_UMLS_SOLR_HOST")
UMLS_SOLR_PORT = os.getenv("MACSS_MEDICAL_IE_UMLS_SOLR_PORT")
UMLS_SOLR_CORE = os.getenv("MACSS_MEDICAL_IE_UMLS_SOLR_CORE")

ENTITY_LINKING_EDIT_DISTANCE = 0
